---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: document
  path: content/home.yaml
  label: Home
- type: directory
  path: content/articles
  label: Articles
  create: documents
  match: "**/*"
  exclude: README.md
  new_doc_ext: md
upload_dir: ''
public_path: https://res.cloudinary.com/luiza-benisano-blog/image/upload/v1631328158/Posts
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
